package ipPhone_util;

import java.io.Serializable;

/**
 * container for any type of object to be sent
 * @author dosse, iblackholmes
 */
public class Message implements Serializable{
    /**
	 * default serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	private int clientID = 0; //-1 means from client to server, otherwise clientID generated by the server
    private long timestamp, //-1 means from client to server, otherwise timeStamp of the moment when the server receives the message
            ttl=2000; //2 seconds TTL
    private Object data; //can carry any type of object. in this program, i used a sound packet, but it could be a string, a chunk of video, ...
    private int channelID;// channel ID for display sound
    
    public Message() {}
    public Message(int clientID, Object data) {
    	this.clientID = clientID;
    	this.data = data;
    }
  
    public Object getData() {
        return data;
    }
    public void setData(Object data) {
    	this.data = data;
    }
    
    public long getTimestamp() {
        return timestamp;
    }
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public long getClientID() {
        return clientID;
    }
    public void setClientID(int clientID) {
        this.clientID = clientID;
    }

    public long getTtl() {
        return ttl;
    }
    public void setTtl(long ttl) {
        this.ttl = ttl;
    }
    
    public int getChannelID() {
    	return this.channelID;
    }
    public void setChannelID(int channelID) {
    	this.channelID = channelID;
    }
    
}
